#
# SITE SETTINGS
#

title: Jump Off The Page Editing

name: Shelby Harbour

email: jumpoffthepageediting@gmail.com

slogan: Enhance Your Writing

# Use a maximun of 150 characters for SEO purposes
description: >- # this means to ignore newlines until "baseurl:"
  Helping writers of all kinds polish + publish with encouragement + expertise.

credits: Site by <a href="https://kaitlinseng.com">Kaitlin Seng</a>

author: Shelby

environment: prod

url: 'https://jumpoffthepageediting.com'
baseurl: "" # the subpath of your site, e.g. /blog

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: 'https://jumpoffthepageediting.com/images/'

# Logo size is 600x80 pixels
logo: "logo-blob.png"
nav-logo: "nav-logo.png"

favicon-32x32                        : 'favicon-32x32.png'

sass:
    sass_dir : _sass
    style    : :compressed


facebook_profileid: 61551224662844
instagram_username: proofedbyshelby

# Build settings
#theme: minima
#plugins:
# - jekyll-seo-tag
# - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
